train:
  learning_rate: 0.001
  batch_size: 32
  epochs: 20
  img_size: [224, 224]
  validation_split: 0.2

model:
  architecture: "baseline_cnn"
  input_shape: [224, 224, 3]
  num_classes: 1
  dropout_rate: 0.5

data:
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  augmentation: true
